[2023-02-27 20:40:21,852]^;WARNING^;88^;_internal.py^;_log()^; * Debugger is active!
[2023-02-27 20:40:21,859]^;INFO^;88^;_internal.py^;_log()^; * Debugger PIN: 998-459-131
[2023-02-27 20:40:21,894]^;INFO^;88^;_internal.py^;_log()^; * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2023-02-27 20:42:02,360]^;INFO^;88^;_internal.py^;_log()^; * Detected change in 'G:\\DataScience_Projects\\Fourth_Project\\Insurance_Premium\\insurancepre\\exception\\__init__.py', reloading
[2023-02-27 20:42:02,722]^;INFO^;88^;_internal.py^;_log()^; * Detected change in 'G:\\DataScience_Projects\\Fourth_Project\\Insurance_Premium\\insurancepre\\exception\\__init__.py', reloading
